// Code generated by MockGen. DO NOT EDIT.
// 基于 Querier[R] 接口的 Mock 实现

package builder

import (
	context "context"
	"iter"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockQuerier 是 Querier 接口的 Mock 实现
type MockQuerier[R any] struct {
	ctrl     *gomock.Controller
	recorder *MockQuerierMockRecorder[R]
}

// MockQuerierMockRecorder 是 MockQuerier 的 Mock 记录器
type MockQuerierMockRecorder[R any] struct {
	mock *MockQuerier[R]
}

// NewMockQuerier 创建新的 Mock 实例
func NewMockQuerier[R any](ctrl *gomock.Controller) *MockQuerier[R] {
	mock := &MockQuerier[R]{ctrl: ctrl}
	mock.recorder = &MockQuerierMockRecorder[R]{mock}
	return mock
}

// EXPECT 返回允许调用者指定预期使用的对象
func (m *MockQuerier[R]) EXPECT() *MockQuerierMockRecorder[R] {
	return m.recorder
}

// Use Mock 实现
func (m *MockQuerier[R]) Use(middleware Middleware[R]) Querier[R] {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Use", middleware)
	return m
}

// Use 记录预期调用
func (mr *MockQuerierMockRecorder[R]) Use(middleware any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockQuerier[R])(nil).Use), middleware)
}

// SetStart Mock 实现
func (m *MockQuerier[R]) SetStart(start uint32) Querier[R] {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStart", start)
	return m
}

// SetStart 记录预期调用
func (mr *MockQuerierMockRecorder[R]) SetStart(start any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStart", reflect.TypeOf((*MockQuerier[R])(nil).SetStart), start)
}

// SetLimit Mock 实现
func (m *MockQuerier[R]) SetLimit(limit uint32) Querier[R] {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLimit", limit)
	return m
}

// SetLimit 记录预期调用
func (mr *MockQuerierMockRecorder[R]) SetLimit(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLimit", reflect.TypeOf((*MockQuerier[R])(nil).SetLimit), limit)
}

// SetNeedTotal Mock 实现
func (m *MockQuerier[R]) SetNeedTotal(needTotal bool) Querier[R] {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNeedTotal", needTotal)
	return m
}

// SetNeedTotal 记录预期调用
func (mr *MockQuerierMockRecorder[R]) SetNeedTotal(needTotal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNeedTotal", reflect.TypeOf((*MockQuerier[R])(nil).SetNeedTotal), needTotal)
}

// SetNeedPagination Mock 实现
func (m *MockQuerier[R]) SetNeedPagination(needPagination bool) Querier[R] {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNeedPagination", needPagination)
	return m
}

// SetNeedPagination 记录预期调用
func (mr *MockQuerierMockRecorder[R]) SetNeedPagination(needPagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNeedPagination", reflect.TypeOf((*MockQuerier[R])(nil).SetNeedPagination), needPagination)
}

// SetFields Mock 实现
func (m *MockQuerier[R]) SetFields(fields ...string) Querier[R] {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SetFields", varargs...)
	return m
}

// SetFields 记录预期调用
func (mr *MockQuerierMockRecorder[R]) SetFields(fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFields", reflect.TypeOf((*MockQuerier[R])(nil).SetFields), fields...)
}

// SetBeforeQueryHook Mock 实现
func (m *MockQuerier[R]) SetBeforeQueryHook(hook BeforeQueryHook) Querier[R] {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBeforeQueryHook", hook)
	return m
}

// SetBeforeQueryHook 记录预期调用
func (mr *MockQuerierMockRecorder[R]) SetBeforeQueryHook(hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBeforeQueryHook", reflect.TypeOf((*MockQuerier[R])(nil).SetBeforeQueryHook), hook)
}

// SetAfterQueryHook Mock 实现
func (m *MockQuerier[R]) SetAfterQueryHook(hook AfterQueryHook[R]) Querier[R] {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAfterQueryHook", hook)
	return m
}

// SetAfterQueryHook 记录预期调用
func (mr *MockQuerierMockRecorder[R]) SetAfterQueryHook(hook any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAfterQueryHook", reflect.TypeOf((*MockQuerier[R])(nil).SetAfterQueryHook), hook)
}

// QueryList Mock 实现
func (m *MockQuerier[R]) QueryList(ctx context.Context) ([]*R, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryList", ctx)
	ret0, _ := ret[0].([]*R)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// QueryList 记录预期调用
func (mr *MockQuerierMockRecorder[R]) QueryList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryList", reflect.TypeOf((*MockQuerier[R])(nil).QueryList), ctx)
}

// SetCursorField Mock 实现
func (m *MockQuerier[R]) SetCursorField(fields ...string) Querier[R] {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SetCursorField", varargs...)
	return m
}

// SetCursorField 记录预期调用
func (mr *MockQuerierMockRecorder[R]) SetCursorField(fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCursorField", reflect.TypeOf((*MockQuerier[R])(nil).SetCursorField), fields...)
}

// SetCursorValue Mock 实现
func (m *MockQuerier[R]) SetCursorValue(values ...any) Querier[R] {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range values {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "SetCursorValue", varargs...)
	return m
}

// SetCursorValue 记录预期调用
func (mr *MockQuerierMockRecorder[R]) SetCursorValue(values ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCursorValue", reflect.TypeOf((*MockQuerier[R])(nil).SetCursorValue), values...)
}

// QueryCursor Mock 实现
func (m *MockQuerier[R]) QueryCursor(ctx context.Context) iter.Seq2[*R, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryCursor", ctx)
	ret0, _ := ret[0].(iter.Seq2[*R, error])
	return ret0
}

// QueryCursor 记录预期调用
func (mr *MockQuerierMockRecorder[R]) QueryCursor(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryCursor", reflect.TypeOf((*MockQuerier[R])(nil).QueryCursor), ctx)
}